"""Actualizar tabla Usuario

Revision ID: 800ca0dc7a0c
Revises: eb51d1c131fe
Create Date: 2025-10-28 21:21:47.481762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800ca0dc7a0c'
down_revision = 'eb51d1c131fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Log_transaccional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Id_log', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Usuario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Tiquet', sa.Integer(), nullable=True))
        batch_op.alter_column('Accion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('Log_transaccional_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('Log_transaccional_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('Log_transaccional_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tiquet', ['Tiquet'], ['Id_Tiquet'])
        batch_op.create_foreign_key(None, 'Usuario', ['Usuario'], ['ID_usuario'])
        batch_op.drop_column('Comentario')
        batch_op.drop_column('Fecha_cambio')
        batch_op.drop_column('tiquet')
        batch_op.drop_column('usuario')
        batch_op.drop_column('ID_log')
        batch_op.drop_column('detalle_cambio')

    with op.batch_alter_table('Nivel_de_Satisfaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_nivel', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Nombre', sa.String(length=255), nullable=True))
        batch_op.drop_column('nivel')
        batch_op.drop_column('Id_satisfaccion')

    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        batch_op.alter_column('Nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_column('Accion')

    with op.batch_alter_table('Rol', schema=None) as batch_op:
        batch_op.alter_column('Nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('Rol_Permiso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_RolPermiso', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('ID_Rol',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('ID_Permiso',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('Ubicaciones', schema=None) as batch_op:
        batch_op.alter_column('Nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('Zona')

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('Apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Apellido', mysql.VARCHAR(length=30), nullable=True))

    with op.batch_alter_table('Ubicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Zona', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('Nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('Rol_Permiso', schema=None) as batch_op:
        batch_op.alter_column('ID_Permiso',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('ID_Rol',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('ID_RolPermiso')

    with op.batch_alter_table('Rol', schema=None) as batch_op:
        batch_op.alter_column('Nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Accion', mysql.ENUM('U', 'D', 'I', 'R'), nullable=False))
        batch_op.alter_column('Nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('Nivel_de_Satisfaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Id_satisfaccion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('nivel', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('Nombre')
        batch_op.drop_column('ID_nivel')

    with op.batch_alter_table('Log_transaccional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle_cambio', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ID_log', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tiquet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Fecha_cambio', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('Comentario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Log_transaccional_ibfk_2'), 'Comentarios', ['Comentario'], ['ID_comentario'])
        batch_op.create_foreign_key(batch_op.f('Log_transaccional_ibfk_1'), 'Tiquet', ['tiquet'], ['Id_Tiquet'])
        batch_op.create_foreign_key(batch_op.f('Log_transaccional_ibfk_3'), 'Usuario', ['usuario'], ['ID_usuario'])
        batch_op.alter_column('Accion',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('Tiquet')
        batch_op.drop_column('Usuario')
        batch_op.drop_column('Id_log')

    # ### end Alembic commands ###
